<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */



$packageNameLower = 'backupmodx'; /* No spaces, no dashes */

$components = array(
    /* These are used to define the package and set values for placeholders */
    'packageName' => 'backupmodx',  /* No spaces, no dashes */
    'packageNameLower' => $packageNameLower,
    'packageDescription' => 'Backup Extra for MODX',
    'version' => '2.0.0',
    'release' => 'pl',
    'author' => 'Jan Dähne',
    'email' => '<https://www.quadro-system.de>',
    'authorUrl' => 'https://www.quadro-system.de',
    'authorSiteName' => "Quadro",
    'packageDocumentationUrl' => 'https://www.quadro-system.de/modx-extras/backup-modx/',
    'copyright' => '2018',

    /* no need to edit this except to change format */
    'createdon' => strftime('%m-%d-%Y'),

    'gitHubUsername' => 'jdaehne',
    'gitHubRepository' => 'BackupMODX',

    /* two-letter code of your primary language */
    'primaryLanguage' => 'en',

    /* Set directory and file permissions for project directories */
    'dirPermission' => 0755,  /* No quotes!! */
    'filePermission' => 0644, /* No quotes!! */

    /* Define source and target directories */

    /* path to MyComponent source files */
    'mycomponentRoot' => $this->modx->getOption('mc.root', null,
        MODX_CORE_PATH . 'components/mycomponent/'),

    /* path to new project root */
    'targetRoot' => MODX_ASSETS_PATH . 'mycomponents/' . $packageNameLower . '/',


    /* *********************** NEW SYSTEM SETTINGS ************************ */

    /* If your extra needs new System Settings, set their field values here.
     * You can also create or edit them in the Manager (System -> System Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra */

    'newSystemSettings' => array(
        'backupmodx_system_setting1' => array( // key
            'key' => 'backupmodx.excludes',
            'name' => 'Exclude Files / Folders',
            'description' => 'Files / Folders to exclude from the Backup. Comma separatet list. Assets Placeholder is available. Example: {assets_path}uploads/',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => '',
            'area' => 'Admin',
        ),
        'backupmodx_system_setting2' => array( // key
            'key' => 'backupmodx.targetPath',
            'name' => 'Backup Target Path',
            'description' => 'The path to the folder to store the backups. Assets Placeholder is available. Example: {core_path}backups/',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => '{core_path}components/backupmodx/backups/',
            'area' => 'Admin',
        ),
        'backupmodx_system_setting3' => array( // key
            'key' => 'backupmodx.cronKey',
            'name' => 'Cron Security Key',
            'description' => 'Security-Key for cron scheduled Backups. Can be any string.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => '',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting4' => array( // key
            'key' => 'backupmodx.mysqldumpAlias',
            'name' => 'Alias mysqldump',
            'description' => 'Alias for mysqldump.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => 'mysqldump',
            'area' => 'Database',
        ),
        'backupmodx_system_setting5' => array( // key
            'key' => 'backupmodx.zipAlias',
            'name' => 'Alias zip',
            'description' => 'Alias for zip compression.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => 'zip',
            'area' => 'Files',
        ),
        'backupmodx_system_setting6' => array( // key
            'key' => 'backupmodx.cronFiles',
            'name' => 'Backup Files',
            'description' => 'Whether or not to include MODX Files in Cron-Backup.',
            'namespace' => 'backupmodx',
            'xtype' => 'combo-boolean',
            'value' => 'true',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting7' => array( // key
            'key' => 'backupmodx.cronDatabase',
            'name' => 'Backup Database',
            'description' => 'Whether or not to include Database in Cron-Backup.',
            'namespace' => 'backupmodx',
            'xtype' => 'combo-boolean',
            'value' => 'true',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting8' => array( // key
            'key' => 'backupmodx.cronNote',
            'name' => 'Note',
            'description' => 'Optional descriptional txt-file added to the Backup.',
            'namespace' => 'backupmodx',
            'xtype' => 'textarea',
            'value' => '',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting9' => array( // key
            'key' => 'backupmodx.cronEnable',
            'name' => 'Enable Cron',
            'description' => 'Enable or Disable Cron.',
            'namespace' => 'backupmodx',
            'xtype' => 'combo-boolean',
            'value' => 'false',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting10' => array( // key
            'key' => 'backupmodx.cronMaxDatabase',
            'name' => 'Max Databases',
            'description' => 'Maximum stored Backups of Database.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => '10',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting11' => array( // key
            'key' => 'backupmodx.cronMaxFiles',
            'name' => 'Max Files',
            'description' => 'Maximum stored Backups of Files.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => '5',
            'area' => 'Cron',
        ),
        'backupmodx_system_setting12' => array( // key
            'key' => 'backupmodx.mysqlAlias',
            'name' => 'Alias mysql',
            'description' => 'Alias for mysql.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => 'mysql',
            'area' => 'Database',
        ),
        'backupmodx_system_setting13' => array( // key
            'key' => 'backupmodx.groups',
            'name' => 'Groups',
            'description' => 'Group or comma separated list of Groups. This Groups will have access to the widget.',
            'namespace' => 'backupmodx',
            'xtype' => 'textfield',
            'value' => 'Administrator',
            'area' => 'Admin',
        ),
    ),


    /* ************************ NAMESPACE(S) ************************* */
    /* (optional) Typically, there's only one namespace which is set
     * to the $packageNameLower value. Paths should end in a slash
    */

    'namespaces' => array(
        'backupmodx' => array(
            'name' => 'backupmodx',
            'path' => '{core_path}components/backupmodx/',
            'assets_path' => '{assets_path}components/backupmodx/',
        ),

    ),



    /* ************************* CATEGORIES *************************** */
    /* (optional) List of categories. This is only necessary if you
     * need to categories other than the one named for packageName
     * or want to nest categories.
    */

    'categories' => array(
        'backupmodx' => array(
            'category' => 'BackupMODX',
            'parent' => '',  /* top level category */
        ),
    ),



    'widgets' => array(
        'BackupMODX' => array(
            'name' => 'BackupMODX',
            'description' => 'Backup MODX Widget',
            'namespace' => 'backupmodx',
            'type' => 'snippet',
            'content' => 'BackupMODXWidget',
            'size' => 'half',
            'lexicon' => 'backupmodx:default',
            'dashboards' => array(
                /* dashboard ID => rank (default dashboard is 1)*/
                1 => 0,
            ),
        ),
    ),


    /* ************************* ELEMENTS **************************** */

    /* Array containing elements for your extra. 'category' is required
       for each element, all other fields are optional.
       Property Sets (if any) must come first!

       The standard file names are in this form:
           SnippetName.snippet.php
           PluginName.plugin.php
           ChunkName.chunk.html
           TemplateName.template.html

       If your file names are not standard, add this field:
          'filename' => 'actualFileName',
    */


    'elements' => array(
        'snippets' => array(
            'BackupMODXWidget' => array(
                'category' => 'backupMODX',
                'description' => 'BackupMODX Dashboard widget.',
                'static' => false,
            ),
        ),
        'chunks' => array(
            'backupMODXWidget' => array(
                'category' => 'backupMODX',
            ),
        ),
    ),
    /* (optional) will make all element objects static - 'static' field above will be ignored */
    'allStatic' => false,


    /* ********************************************* */
    /* Define optional directories to create under assets.
     * Add your own as needed.
     * Set to true to create directory.
     * Set to hasAssets = false to skip.
     * Empty js and/or css files will be created.
     */
    'hasAssets' => true,

    'assetsDirs' => array(
        /* If true, a default (empty) CSS file will be created */
        'css' => false,

        /* If true, a default (empty) JS file will be created */
        'js' => false,

        'images' => false,
        'audio' => false,
        'video' => false,
        'themes' => false,
    ),
    /* minify any JS files */
    'minifyJS' => false,
    /* Create a single JS file from all JS files */
    'createJSMinAll' => false,
    /* if this is false, regular jsmin will be used.
       JSMinPlus is slower but more reliable */
    'useJSMinPlus' => false,

    /* These will automatically go under assets/components/yourcomponent/js/
       Format: directory:filename
       (no trailing slash on directory)
       if 'createCmpFiles is true, these will be ignored.
    */
    'jsFiles' => array(),

    /* Desired CSS files */
    'cssFiles' => array(),

    /* ********************************************* */
    /* Define basic directories and files to be created in project*/

    'docs' => array(
        'readme.txt',
        'license.txt',
        'changelog.txt',
        'tutorial.html'
    ),

    /* (optional) Description file for GitHub project home page */
    'readme.md' => false,
    /* assume every package has a core directory */
    'hasCore' => true,

    /* ********************************************* */
    /* (optional) Array of extra script resolver(s) to be run
     * during install. Note that resolvers to connect plugins to events,
     * property sets to elements, resources to templates, and TVs to
     * templates will be created automatically -- *don't* list those here!
     *
     * 'default' creates a default resolver named after the package.
     * (other resolvers may be created above for TVs and plugins).
     * Suffix 'resolver.php' will be added automatically */
    'resolvers' => array(
        'default'
    ),

    /* (optional) Validators can abort the install after checking
     * conditions. Array of validator names (no
     * prefix of suffix) or '' 'default' creates a default resolver
     *  named after the package suffix 'validator.php' will be added */

    'validators' => array(),

    /* (optional) install.options is needed if you will interact
     * with user during the install.
     * See the user.input.php file for more information.
     * Set this to 'install.options' or ''
     * The file will be created as _build/install.options/user.input.php
     * Don't change the filename or directory name. */
    'install.options' => 'install.options',


    /* Suffixes to use for resource and element code files (not implemented)  */
    'suffixes' => array(
        'modPlugin' => '.php',
        'modSnippet' => '.php',
        'modChunk' => '.html',
        'modTemplate' => '.html',
        'modResource' => '.html',
    ),


    /* ********************************************* */
    /* (optional) Only necessary if you will have class files.
     *
     * Array of class files to be created.
     *
     * Format is:
     *
     * 'ClassName' => 'directory:filename',
     *
     * or
     *
     *  'ClassName' => 'filename',
     *
     * ('.class.php' will be appended automatically)
     *
     *  Class file will be created as:
     * yourcomponent/core/components/yourcomponent/model/[directory/]{filename}.class.php
     * Note: If a CMP is being created, classes containing the
     * project name will be ignored here.
     *
     * Set to array() if there are no classes. */
    'classes' => array(
        'AnotherClass' => 'backupmodx:backupmodx',

        /* (optional) - Specify methods for each class.
           if 'function' is missing, 'public function ' will
           be prepended. Curly braces will be added   */
        'methods' => array(),
    ),

    /* ************************************
     *  These values are for CMPs.
     *  Set any of these to an empty array if you don't need them.
     *  **********************************/

    /* If this is false, the rest of this section will be ignored */

    'createCmpFiles' => false,

    /* IMPORTANT: The array values in the rest of
       this section should be all lowercase */

    /* This is the main action file for your component.
       It will automatically go in core/component/yourcomponent/
    */

    'actionFile' => 'index.class.php',

    /* CSS file for CMP */

    'cssFile' => 'mgr.css',

    /* These will automatically go to core/components/yourcomponent/processors/
       format directory:filename
       '.class.php' will be appended to the filename

       Built-in processor classes include getlist, create, update, duplicate,
       import, and export. */

    'processors' => array(
        'mgr/snippet:getlist',
        'mgr/snippet:changecategory',
        'mgr/snippet:remove',

        'mgr/chunk:getlist',
        'mgr/chunk:changecategory',
        'mgr/chunk:remove',
    ),

    /* These will automatically go to core/components/yourcomponent/controllers[/directory]/filename
       Format: directory:filename */

    'controllers' => array(
        ':home.class.php',
    ),

    /* These will automatically go in assets/components/yourcomponent/ */

    'connectors' => array(
        'connector.php'

    ),
    /* These will automatically go to assets/components/yourcomponent/js[/directory]/filename
       Format: directory:filename */

    'cmpJsFiles' => array(
        ':backupmodx.class.js',
        'sections:home.js',
        'widgets:home.panel.js',
        'widgets:snippet.grid.js',
        'widgets:chunk.grid.js',
    ),

    /* These go to core/components/componentName/templates/
     * The format is:
     *    filename:content
     * content is optional
     */

    'cmpTemplates' => array (
         'mgr:<div id="backupmodx-panel-home-div"></div>',
    ),


    /* *******************************************
     * These settings control exportObjects.php  *
     ******************************************* */
    /* ExportObjects will update existing files. If you set dryRun
       to '1', ExportObjects will report what it would have done
       without changing anything. Note: On some platforms,
       dryRun is *very* slow  */

    'dryRun' => '0',

    /* Array of elements to export. All elements set below will be handled.
     *
     * To export resources, be sure to list pagetitles and/or IDs of parents
     * of desired resources
    */
    'process' => array(
        'snippets',
        'propertySets',
        'systemSettings'
    ),
    /*  Array  of resources to process. You can specify specific resources
        or parent (container) resources, or both.

        They can be specified by pagetitle or ID, but you must use the same method
        for all settings and specify it here. Important: use IDs if you have
        duplicate pagetitles */
    'getResourcesById' => false,

    'exportResources' => array(),
    /* Array of resource parent IDs to get children of. */
    'parents' => array(),
    /* Also export the listed parent resources
      (set to false to include just the children) */
    'includeParents' => false,


    /* ******************** LEXICON HELPER SETTINGS ***************** */
    /* These settings are used by LexiconHelper */
    'rewriteCodeFiles' => false,  /* remove ~~descriptions */
    'rewriteLexiconFiles' => false, /* automatically add missing strings to lexicon files */
    /* ******************************************* */

    /* Array of aliases used in code for the properties array.
     * Used by the checkproperties utility to check properties in code against
     * the properties in your properties transport files.
     * if you use something else, add it here (OK to remove ones you never use.
     * Search also checks with '$this->' prefix -- no need to add it here. */
    'scriptPropertiesAliases' => array(
        'props',
        'sp',
        'config',
        'scriptProperties'
    ),
);

return $components;
